image:
  - Visual Studio 2019
before_build:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - cmd: vendor/apache-ant-1.10.7/bin/ant -buildfile build.xml clean
  - cmd: vendor/apache-ant-1.10.7/bin/ant -buildfile build.xml test
